language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
before_script: 
  - python manage.py migrate
  - python manage.py collectstatic --noinput
script:
  - black --check .
  - flake8 --max-line-length=92 .
  - coverage run manage.py test
after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "mysite"
  env: "mysite-dev"
  bucket_name: "elasticbeanstalk-us-east-1-207567791591"
  on:
    branch: main